### PR TITLE
Make FLiT installable, but breaks some functionality

### PR DESCRIPTION
**Pull request by mikebentley15**
This work is a significant refactoring of the FLiT tool and repository.  It breaks much of the existing functionality such database integration and remote server automation.  Those things definitely need to get fixed or reimplemented.

This change introduces a new flit command-line tool.  Not all of the subcommands are implemented yet.  The ones that are can be seen below with their descriptions:

- `flit help`: show help documentation for any of the subcommands
- `flit init`: initializes a directory to be able to compile FLiT tests.  Adds the following files into the folder:
  - `main.cpp`: a very small main function
  - `flit-config.toml`: a configuration file configuring the behavior of the flit command-line tool
  - `tests/Empty.cpp`: an example FLiT test that does nothing.  Basically a template for use.
  - `Makefile`: autogenerated from `flit-config.toml`.  This makefile has two important targets:
    - `make dev`: Compile only one executable from the tests for the sake of aiding in developing the tests
    - `make run`: Compile all different versions of the tests using multiple compilers and compiler options, storing the results in a new directory `results/`.
- `flit update`: Regenerate the `Makefile` using `flit-config.toml`.  More implementation required since not all of the configurations from the configuration file are used yet.

Other subcommands to still be implemented:

- `flit run`: Login to the hosts specified in `flit-config.toml` and run `make update --host <name>` then `make run` followed by inserting the results into the database.
- `flit check`: verifies `flit-config.toml` and gives human-readable error messages and warning messages describing what needs fixing and suggesting ways to fix it.
- `flit analyze`: runs analysis based on the data in the configured database.  The files created under the analysis will be under a new directory called `analysis/`

Other things done in this change set:

- Make FLiT be compiled into a shared library `libflit.so`
- Add minimal support for Mac OSX for the non-broken features
- Put a `Makefile` at the top-level with a `make install` target that takes a `PREFIX` override (e.g. `make install PREFIX=~/my-installs/`).  The default `PREFIX` is `/usr` which is pretty standard.  This will install into the following directory structure:

```
prefix/
 |-- bin/flit -> ../share/flit/script/flit.py
 |-- lib/libflit.so
 |-- include/*.h (FLiT header files; most notably flit.h which includes all of them)
 +-- share/flit/
     |-- scripts/
     |   |-- flit.py
     |   |-- flit_*.py (subcommands)
     |   |-- flitconfig.py (contains paths to things)
     |   +-- flitutil.py (contains functions shared between subcommands)
     |-- doc/*
     |-- data/
     |   |-- tests/Empty.cpp
     |   |-- Makefile.in
     |   |-- custom.mk
     |   +-- main.cpp
     |-- litmus-tests/
     |   |-- *.cpp
     |   |-- *.hpp
     |   +-- *.h
     +-- config/flit-default.toml.in
```

_**Note:** This change does not update the documentation yet.  That is also something that is yet to be done._

I chose to do the pull request now since the change set was getting a little too large and should be split up into more individual tasks.  But it is at a good stopping point as it is usable as-is without database support or multiple host support.  Those are things to be added back in.

This fixes issue #42 and issue #47 and starts a fix for issue #44 and issue #41.

### CODE REVIEW

**Comment by mikebentley15** [comment]
@Geof23 you can consider yourself an optional reviewer.  As the originator of the FLiT tool, I highly value your input.
@IanBriggs please review as much as you feel comfortable.  You can either look at the changes, test the changes, or both.  I appreciate the help 😃

**Comment by ganeshutah** [comment]
Wow, ambitious set of tasks!!

**Comment by mikebentley15** [comment]
Thanks Ganesh.  I can give you a demo tomorrow.

**Comment by mikebentley15** [comment]
Well, since nobody has shown interest in this work yet, I'm going to merge in this pull request.

**Pull request merged**
